version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: IntegrationTests!
      MYSQL_DATABASE: it_test
      MYSQL_USER: it_user
      MYSQL_PASSWORD: IntegrationTests!
  oracle:
    image: wnameless/oracle-xe-11g
    ports:
      - "1521:1521"
  mssql:
    image: microsoft/mssql-server-linux
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: IntegrationTests!
